// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfjywjvpzytqlipwmaki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmanl3anZwenl0cWxpcHdtYWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTYzMzgsImV4cCI6MjA2NDkzMjMzOH0.4lNmkHD4FxDuOPCfcZupokQnyLOoYlyyeZrZxb3iYe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);